### ISSUE TITLE
Text Align

### ISSUE THREAD

**Issue by Amirk390** [FACN3/mrrobot_project2#17]
i think the text instead of being centered to the center it should be centered to the right 
`text-align: right;`
https://github.com/FACN3/mrrobot_project2/blob/master/style.css#L63

that way it is easier to delete a todo task faster by just clicking on the delete button at the same location each time 
![image](https://user-images.githubusercontent.com/24490876/32595987-7b3ac17c-c53a-11e7-8d0a-3de2a39a81e3.png)

**Comment by sophiavocado** [comment]
I was the one who insisted to center them, personal preference  🤓  but yeah, also makes sense!
