### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by matthewdking** [FACN3/mrrobot_project2#7]
Console logs are a great way for you to understand your code! However you should remove them before merging into master. Good to see you are using them though :+1: 

PS I see you tried to remove them but [one](https://github.com/FACN3/mrrobot_project2/blob/master/logic.js#L46) slipped through

**Comment by matthewdking** [comment]
UPDATE: I have found a few more throughout your file. Please go through carefully and delete them

**Comment by SamiSha99** [comment]
@matthewdking done
