### ISSUE TITLE
Page size

### ISSUE THREAD

**Issue by Amirk390** [FACN3/mrrobot_project2#9]
the width and height values ion the style.css isn't necessary in my opinion 
the page will look the same without them, and at the moment the page is to big with them. :smile: 
```
.frame {

  width: 100vw;

  height: 100vh;

  text-align: center;

}
```

https://github.com/FACN3/mrrobot_project2/blob/master/style.css#L32

**Comment by SamiSha99** [comment]
This effect won't be seen on large webpages, however it does take an effect on smaller devices

With .frame: https://prnt.sc/h85rb8

Without .frame: https://prnt.sc/h85qve

There is difference, I think there is no point in remove that.
